import { FC, ReactNode } from 'react';
import { Poppins } from 'next/font/google';
import type { Metadata } from 'next';
import '@/styles/globals.scss';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
    icons: {
        icon: '/favicon.ico',
    },
};

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '500', '600'],
});

interface IRootLayout {
    children: ReactNode;
}

const RootLayout: FC<IRootLayout> = ({ children }) => {
    return (
        <html lang="en">
            <body className={poppins.className}>{children}</body>
        </html>
    );
};

export default RootLayout;
